Add a docker compose file for dev
LAB-MI/attestation-deplacement-derogatoire-q4-2020 pull request #119
Opened 2020-11-03 18:09 UTC by jmleroux

J'ai voulu commencer à tester cette appli et je n'ai pas l'environnement nécessaire pour la faire tourner.
Cette proposition permet d'ajouter un container Docker et ainsi éviter d'installer node et/ou npm sur la machine du developpeur.

2020-11-03 19:11 UTC, a2br commented on README.md
> +```console
Je crois que c'est plutôt `shell` que `console`

2020-11-03 20:58 UTC, gjgd commented on docker-compose.yml
> +      - ./:/srv/jmleroux
peut-etre un nom plus générique pour le nom du working_dir genre `/srv/app` ?

2020-11-03 21:15 UTC, jmleroux commented on docker-compose.yml
> +      - ./:/srv/jmleroux
oups, l'habitude... je corrige bien evidemment

2020-11-03 22:44 UTC, sadwolf996 requested changes

2020-11-03 22:44 UTC, sadwolf996 commented on docker-compose.yml
> +    image: node:10
Node v10 n'est plus une LTS active depuis octobre 2018. Node v12 ne sera plus non plus une LTS active d'ici la fin du mois. La seule LTS viable et active aujourd'hui est la version 14.

![image](https://user-images.githubusercontent.com/73841663/98048631-62cf1700-1e2e-11eb-9b6c-3ae4f4fec669.png)

2020-11-03 23:36 UTC, jmleroux commented
Duplicate of #64 by the way. N'hésitez pas à fermer si nécessaire.

2020-12-10 08:34 UTC, jmleroux commented
Pas beaucoup de réponses aux PR sur ce répo...

2020-12-10 08:34 UTC, closed without merging