Ajout de l'heure actuelle en valeur par défaut de l'heure de sortie
LAB-MI/attestation-deplacement-derogatoire-q4-2020 pull request #44
Opened 2020-10-30 12:07 UTC by devSwoop

Petit truc tout bête qui peut être utile

2020-10-30 13:44 UTC, mabhub requested changes

2020-10-30 13:44 UTC, mabhub commented on src/js/form.js
> +}
```suggestion
const setCurrentTime = input => {
  const fullDate = new Date();
  const time = fullDate.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });

  input.value = time;
}
```

Mais il serait plus propre de simplement retourner la valeur, et modifier l'input là où la fonction est appelée.

```suggestion
const getCurrentTime = () => {
  const date = new Date();
  return date.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
}
```

avec plus loin :
```js
input.value = getCurrentTime();
// au lieu de: `setCurrentTime(input)`
```

2020-10-30 13:44 UTC, mabhub commented on src/js/form.js
> +    setCurrentTime(input)
```suggestion
    input.value = getCurrentTime()
```

2020-10-30 14:41 UTC, devSwoop commented on src/js/form.js
> +}
Bien vu pour le formatage, j'avoue que je ne connaissais pas ça 👍

2020-10-30 14:41 UTC, devSwoop commented on src/js/form.js
> +    setCurrentTime(input)
J'avais hésité à faire comme ça (je préfère aussi), et comme j'avais vu de la modification directe de ce genre dans le code, j'ai choisis de le faire aussi.

2020-10-30 15:19 UTC, merged

2020-10-31 10:49 UTC, mabhub commented
Une idée de *quand* ce sera déployé ?