Correction de l'erreur de service worker
LAB-MI/attestation-deplacement-derogatoire-q4-2020 pull request #93
Opened 2020-11-01 15:56 UTC by mbrechet

Le chargement de l'application provoque une erreur au niveau du service worker

`VM13 main.d56e3230.js:27 [SW ERROR] TypeError: Failed to register a ServiceWorker for scope ('https://media.interieur.gouv.fr/') with script ('https://media.interieur.gouv.fr/sw.js'): A bad HTTP response code (404) was received when fetching the script.`

Cette PR prend en compte le chemin de l'application pour l'enregistrement du service worker ce qui lui permet de fonctionner depuis un sous répertoire

2020-11-01 23:08 UTC, bastienmoulia requested changes

2020-11-01 23:08 UTC, bastienmoulia commented on src/js/check-updates.js
> +    navigator.serviceWorkers
Sans le `s` à navigator.serviceWorkers

2020-11-02 07:38 UTC, mbrechet commented on src/js/check-updates.js
> +    navigator.serviceWorkers
:+1: Bien vu je ne sais pas pourquoi ce s s'est glissé ici, je viens de fix

2020-11-02 16:22 UTC, betalabmi approved these changes

2020-11-02 16:22 UTC, merged